project_id = "xmpjqtvznswcdfwtrvpc"

[functions.initiate-outbound-call]
verify_jwt = true

[functions.handle-call-webhook]
verify_jwt = false

[functions.ai-conversation-handler]
verify_jwt = false

[functions.ai-script-generator]
verify_jwt = true

[functions.speech-to-text]
verify_jwt = true

[functions.text-to-speech]
verify_jwt = true

[functions.voice-quality-analyzer]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.track-usage]
verify_jwt = true

# Call reliability system functions
[functions.call-retry-handler]
verify_jwt = true

[functions.call-state-monitor]
verify_jwt = false

[functions.campaign-queue-manager]
verify_jwt = false

[functions.call-error-recovery]
verify_jwt = false